### ISSUE TITLE
 undefined method `to_str`

### ISSUE THREAD

**Issue by PhML** [doudou/snapsync#4] opened 2016-05-13 21:31 UTC
I've got an error on my first execution:

```
sudo /opt/snapsync/bin/snapsync init --no-all photos /run/media/me/backup1To/                                                                                                                                        
[sudo] Mot de passe de me : 
 INFO  Snapsync : initialized /run/media/me/backup1To/root as a snapsync target
 INFO  Snapsync : initialized /run/media/me/backup1To/photos as a snapsync target
/opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/partitions_monitor.rb:28:in `monitor_for': undefined method `to_str' for nil:NilClass (NoMethodError)
Did you mean?  to_s
               to_r
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/auto_sync.rb:137:in `add'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/cli.rb:234:in `auto_add'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/cli.rb:197:in `init'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/bin/snapsync:4:in `<top (required)>'
        from /opt/snapsync/bin/snapsync:12:in `load'
        from /opt/snapsync/bin/snapsync:12:in `<main>'
```

_**Note 1** same error without options_
_**Note 2**  root profile was used while I expected not with the `--no-all` option enabled_

Then with debug enabled:

```
sudo /opt/snapsync/bin/snapsync init --no-all --debug photos /run/media/me/backup1To/
/opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/cli.rb:134:in `init': cannot use --auto without --all (ArgumentError)
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/bin/snapsync:4:in `<top (required)>'
        from /opt/snapsync/bin/snapsync:12:in `load'
        from /opt/snapsync/bin/snapsync:12:in `<main>'
```

So I tried with the `--no-auto` option:

```
 sudo /opt/snapsync/bin/snapsync init --no-all --no-auto photos /run/media/me/backup1To/
/opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/cli.rb:134:in `init': cannot use --auto without --all (ArgumentError)
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/bin/snapsync:4:in `<top (required)>'
        from /opt/snapsync/bin/snapsync:12:in `load'
        from /opt/snapsync/bin/snapsync:12:in `<main>'
```

And then with debug again:

```
sudo /opt/snapsync/bin/snapsync init --no-all --no-auto --debug photos /run/media/me/backup1To/                                                                                                                       
/opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/cli.rb:165:in `rescue in init': --auto is not set but it seems that you provided a name (ArgumentError)
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/lib/snapsync/cli.rb:151:in `init'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/snapsync/bundle/ruby/2.3.0/gems/snapsync-0.3.3/bin/snapsync:4:in `<top (required)>'
        from /opt/snapsync/bin/snapsync:12:in `load'
        from /opt/snapsync/bin/snapsync:12:in `<main>'
```

Last try:

```
sudo /opt/snapsync/bin/snapsync init /run/media/me/backup1To/
ERROR: "snapsync init" was called with arguments ["/run/media/me/backup1To/"]
Usage: "snapsync init [NAME] DIR [POLICY]"
```

**Comment by doudou** [comment] 2016-05-16 16:14
Hi ... sorry for the confusion.

Most of your troubles are caused because of a bug in thor, where the `--no-XXX` argument are actually not always parsed properly. Always use `--XXX=f` to disable a boolean flag for tools using thor (I've updated the readme to reflect this). I have to have a look at whether I can avoid having thor show the `--no-` variant in the help message.

The first error you got seemed to be caused by snapsync not being able to detect the partition UUID of the underlying partition. I've pushed a fix to get a proper error message (in 0.3.4)

The other ones are a misunderstanding (and lack of documentation in the README) on how to use snapsync manually.

The snapsync target is not linked to a snapper configuration. It's just a snapsync target. You're the one that will decide to which snapper configuration it is associated with at synchronization time (and you have to make sure you always use the same snapper configuration in all subsequent sync calls, snapsync does not do any sanity checks there)

```
snapsync init --all=f --auto=f /path/to/target
snapsync sync photos /path/to/target
```

Thank you for the patience you've shown while trying snapsync out !

**Closed as completed** 2017-07-27 15:50 UTC
